export const stores = [
  { id: 'store_hq', name: 'TEMPUR 品牌总部', city: '上海' },
  { id: 'store_sz', name: '苏州体验店', city: '苏州' },
  { id: 'store_nj', name: '南京体验店', city: '南京' },
  { id: 'store_wx', name: '无锡滨湖店', city: '无锡' },
];

export const users = [
  { phone: 'admin', password: 'admin123', name: '总部管理员', role: 'admin', storeId: 'store_hq', city: '上海' },
  { phone: 'dealer001', password: '123456', name: '苏州店长', role: 'dealer_owner', storeId: 'store_sz', city: '苏州' },
  { phone: 'sales001', password: '123456', name: '苏州导购A', role: 'sales', storeId: 'store_sz', city: '苏州' },
  { phone: 'installer001', password: '123456', name: '苏州安装师傅', role: 'installer', storeId: 'store_sz', city: '苏州', team: '安装团队A' },
  { phone: 'dealer002', password: '123456', name: '南京店长', role: 'dealer_owner', storeId: 'store_nj', city: '南京' },
  { phone: 'sales002', password: '123456', name: '南京导购A', role: 'sales', storeId: 'store_nj', city: '南京' },
  { phone: 'installer002', password: '123456', name: '南京安装师傅', role: 'installer', storeId: 'store_nj', city: '南京', team: '安装团队B' },
  { phone: 'dealer003', password: '123456', name: '无锡店长', role: 'dealer_owner', storeId: 'store_wx', city: '无锡' },
  { phone: 'sales003', password: '123456', name: '无锡导购A', role: 'sales', storeId: 'store_wx', city: '无锡' },
  { phone: 'installer003', password: '123456', name: '无锡安装师傅', role: 'installer', storeId: 'store_wx', city: '无锡', team: '安装团队C' },
];

export const products = [
  {
    id: 'tempur-pro-yiran-soft',
    series: 'Pro Air 梵璞·怡然',
    model: '柔软款',
    category: '床垫',
    customerPageCopy: '适合喜欢包裹感、侧睡较多的客户。',
    images: ['/assets/images/products/tempur-pro-yiran-soft.jpg'],
  },
  {
    id: 'tempur-form-original',
    series: 'TEMPUR FORM',
    model: '原感款',
    category: '床垫',
    customerPageCopy: '经典承托，适合需要稳定支撑的家庭卧室。',
    images: ['/assets/images/products/tempur-form-original.jpg'],
  },
  {
    id: 'tempur-smart-ergo',
    series: 'Smart Ergo',
    model: '智能床',
    category: '智能床',
    customerPageCopy: '适合想改善阅读、观影和睡眠姿态的客户。',
    images: ['/assets/images/products/tempur-smart-ergo.jpg'],
  },
];

export const deliveryTasks = [
  {
    id: 'pilot-sz-001',
    storeId: 'store_sz',
    storeName: '苏州体验店',
    salesId: 'sales001',
    salesName: '苏州导购A',
    installerId: 'installer001',
    installerName: '苏州安装师傅',
    customerAlias: '苏州王女士',
    city: '苏州',
    scene: '主卧',
    brand: 'TEMPUR',
    model: 'Pro Air 梵璞·怡然 柔软款',
    productName: 'TEMPUR Pro Air',
    productSeries: '梵璞·怡然',
    productCategory: '床垫',
    productModel: '柔软款',
    reviewStatus: 'approved',
    installImages: ['/assets/images/case-suzhou-bedroom-01.png'],
    storyPublic: '客户原先侧睡肩颈不适，试睡后选择柔软款提升包裹感。',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pilot-nj-001',
    storeId: 'store_nj',
    storeName: '南京体验店',
    salesId: 'sales002',
    salesName: '南京导购A',
    installerId: 'installer002',
    installerName: '南京安装师傅',
    customerAlias: '南京陈先生',
    city: '南京',
    scene: '次卧',
    brand: 'TEMPUR',
    model: 'TEMPUR FORM 原感款',
    productName: 'TEMPUR FORM',
    productSeries: 'FORM',
    productCategory: '床垫',
    productModel: '原感款',
    reviewStatus: 'approved',
    installImages: ['/assets/images/case-suzhou-bedroom-02.png'],
    storyPublic: '客户关注腰部承托，门店体验后选择更稳定的经典支撑。',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pilot-wx-001',
    storeId: 'store_wx',
    storeName: '无锡滨湖店',
    salesId: 'sales003',
    salesName: '无锡导购A',
    installerId: 'installer003',
    installerName: '无锡安装师傅',
    customerAlias: '无锡李女士',
    city: '无锡',
    scene: '主卧',
    brand: 'TEMPUR',
    model: 'Smart Ergo 智能床',
    productName: 'Smart Ergo',
    productSeries: '智能床',
    productCategory: '智能床',
    productModel: 'Smart Ergo',
    reviewStatus: 'approved',
    installImages: ['/assets/images/delivery-bedroom-01.jpg'],
    storyPublic: '客户希望睡前阅读更舒适，选择智能床搭配床垫方案。',
    createdAt: new Date().toISOString(),
  },
];

export const materials = [
  {
    id: 'pilot-material-001',
    title: '真实交付案例朋友圈模板',
    category: 'moments',
    categoryLabel: '朋友圈',
    content: '今天完成一户 TEMPUR 交付，客户最满意的是支撑和包裹感的平衡。',
    platforms: ['朋友圈'],
    scene: '交付',
    images: ['/assets/images/delivery-bedroom-01.jpg'],
    isRecommended: true,
    createdAt: new Date().toISOString(),
  },
];
